package com.ultimatevoicegenerator;
import java.text.Normalizer;
import java.util.*;
import java.util.regex.*;
import org.json.*;
final class TextRules {
 static String clean(String s){return Normalizer.normalize(s,Normalizer.Form.NFC).replaceAll("\\s+"," ").trim();}
 static List<String> tokens(String s){Matcher m=Pattern.compile("[\\p{L}\\p{N}]+").matcher(Normalizer.normalize(s,Normalizer.Form.NFKC).toLowerCase(Locale.ROOT).replace("’", "").replace("'",""));List<String> out=new ArrayList<>();while(m.find())out.add(m.group());return out;}
 static String pronounce(String text,JSONArray rules)throws Exception{if(rules==null||rules.length()==0)return text;Map<String,String> map=new HashMap<>();List<String> keys=new ArrayList<>();for(int i=0;i<rules.length();i++){JSONObject r=rules.getJSONObject(i);String word=r.getString("word");keys.add(word);map.put(word.toLowerCase(Locale.ROOT),r.getString("sayAs"));}keys.sort(Comparator.comparingInt(String::length).reversed());String pattern="(?<![\\p{L}\\p{N}])(?:"+String.join("|",keys.stream().map(Pattern::quote).toList())+")(?![\\p{L}\\p{N}])";Matcher m=Pattern.compile(pattern,Pattern.CASE_INSENSITIVE|Pattern.UNICODE_CASE).matcher(text);StringBuffer result=new StringBuffer();while(m.find())m.appendReplacement(result,Matcher.quoteReplacement(map.get(m.group().toLowerCase(Locale.ROOT))));m.appendTail(result);return result.toString();}
 static JSONObject compare(String expected,String actual,JSONArray rules)throws Exception{List<String>a=tokens(expected),b=tokens(actual);if(!a.equals(b))b=tokens(pronounce(actual,rules));if(a.size()>3000||b.size()>3000)throw new IllegalArgumentException("Transcript too long");int[][] d=new int[a.size()+1][b.size()+1];for(int i=0;i<=a.size();i++)d[i][0]=i;for(int j=0;j<=b.size();j++)d[0][j]=j;for(int i=1;i<=a.size();i++)for(int j=1;j<=b.size();j++)d[i][j]=Math.min(d[i-1][j]+1,Math.min(d[i][j-1]+1,d[i-1][j-1]+(a.get(i-1).equals(b.get(j-1))?0:1)));
  List<String> diff=new ArrayList<>();int x=a.size(),y=b.size();while(x>0||y>0){if(x>0&&y>0&&d[x][y]==d[x-1][y-1]+(a.get(x-1).equals(b.get(y-1))?0:1)){if(!a.get(x-1).equals(b.get(y-1)))diff.add("Expected ‘"+a.get(x-1)+"’, heard ‘"+b.get(y-1)+"’");x--;y--;}else if(x>0&&d[x][y]==d[x-1][y]+1)diff.add("Missing ‘"+a.get(--x)+"’");else diff.add("Extra ‘"+b.get(--y)+"’");}Collections.reverse(diff);int errors=d[a.size()][b.size()];return new JSONObject().put("transcript",actual).put("expected",expected).put("errors",errors).put("passed",errors==0).put("wordErrorRate",errors/(double)Math.max(1,a.size())).put("differences",new JSONArray(diff));}
}
