<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType><TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable>
    <AssemblyName>Ultimate Voice Generator</AssemblyName><ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>../assets/ultimate_voice_generator.ico</ApplicationIcon>
    <Product>Ultimate Voice Generator</Product><Title>Ultimate Voice Generator</Title><Version>3.2.1</Version>
    <RestorePackagesPath>../.nuget</RestorePackagesPath>
  </PropertyGroup>
  <ItemGroup><PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2903.40" /></ItemGroup>
  <Target Name="RemoveUnusedWpfReference" BeforeTargets="ResolveAssemblyReferences"><ItemGroup><Reference Remove="@(Reference)" Condition="'%(Reference.Filename)' == 'Microsoft.Web.WebView2.Wpf'" /></ItemGroup></Target>
</Project>
